Ngo/FinalProj/FinalProj/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()

Ngo/FinalProj/accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('ngo/register/',views.ngo_register,name='ngo_register'),
    path('accountcreate/',views.accountcreate,name='accountcreate'),
    path('ngodetail/',views.ngodetail,name='ngodetail'),
    path('create/', views.edit_view_add, name='edit_view_add'),
    path('delete/',views.delete_view, name='delete_view'),
    path('edit/',views.edit_view, name='edit_view'),
    path('donate/',views.donator_view,name='donator'),
    path('donate/<phone>/',views.donation_confirm,name='don_confirm'),
    path('change-password/', views.MyPasswordChangeView.as_view(), name='reset'),
    path('ngodetail/donators/', views.donators, name='donators'),
    path('donater/signup/',views.d_signup,name='d_signup'),
    path('donators/', views.donators, name='donators'),
    path('contact/',views.contactus, name='contact')
    ]

Ngo/FinalProj/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Ngo(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    founder = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class NgoRequirementDetail(models.Model):
    ngo = models.ForeignKey(Ngo, on_delete=models.CASCADE)
    req = models.CharField(max_length=100)
    quantity = models.IntegerField()

    def __str__(self):
        return self.req


class Donator(models.Model):
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.phone


class DonationDetail(models.Model):
    donator = models.ForeignKey(Donator, on_delete=models.CASCADE)
    ngo = models.ForeignKey(Ngo, on_delete=models.CASCADE)
    req = models.CharField(max_length=100, default='')
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.donator)

Ngo/FinalProj/templates/home.html
{% load check %}
<html>
<title>Homepage</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4 {font-family:"Lato", sans-serif}
.mySlides {display:none}
.w3-tag, .fa {cursor:pointer}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px}

@property --num {
  syntax: "<integer>";
  initial-value: 0;
  inherits: false;
}

.count {
  transition: --num 4s;
  counter-set: num var(--num);
  font: 800 40px system-ui;
}
.count::after {
  content: counter(num);
}
.count:hover {
  --num: {{count}};
}
ul,li{
  list-style:none;
}
ul{
  overflow:hidden;
  padding:3em;
}
ul li a{
  text-decoration:none;
  color:#000;
  background:#bfbfbf;
  display:block;
  height:25em;
  width:25em;
  -moz-box-shadow:5px 5px 7px rgba(33,33,33,1);
  -webkit-box-shadow: 5px 5px 7px rgba(33,33,33,.7);
  box-shadow: 5px 5px 7px rgba(33,33,33,.7);
  -moz-transition:-moz-transform .15s linear;
  -o-transition:-o-transform .15s linear;
  -webkit-transition:-webkit-transform .15s linear;
}
ul li{
  margin:1em;
  float:left;
}
ul li h2{
  padding-top: 10px;
  font-family: 'Times New Roman', Times, serif;
  font-size:180%;
  font-weight:bold;
  padding-bottom:10px;
}
ul li p{
  font-family:"Reenie Beanie",arial,sans-serif;
  font-size:120%;
}
ul li a{
  -webkit-transform: rotate(-6deg);
  -o-transform: rotate(-6deg);
  -moz-transform:rotate(-6deg);
}
ul li:nth-child(even) a{
  -o-transform:rotate(4deg);
  -webkit-transform:rotate(4deg);
  -moz-transform:rotate(4deg);
  position:relative;
  top:5px;
  background:#f2f2f2;
}
ul li:nth-child(3n) a{
  -o-transform:rotate(-3deg);
  -webkit-transform:rotate(-3deg);
  -moz-transform:rotate(-3deg);
  position:relative;
  top:-5px;
  background:#bfbfbf;
}
ul li:nth-child(5n) a{
  -o-transform:rotate(5deg);
  -webkit-transform:rotate(5deg);
  -moz-transform:rotate(5deg);
  position:relative;
  top:-10px;
}
ul li a:hover,ul li a:focus{
  box-shadow:10px 10px 7px rgba(0,0,0,.7);
  -moz-box-shadow:10px 10px 7px rgba(0,0,0,.7);
  -webkit-box-shadow: 10px 10px 7px rgba(0,0,0,.7);
  -webkit-transform: scale(1.25);
  -moz-transform: scale(1.25);
  -o-transform: scale(1.25);
  position:relative;
  z-index:5;
}
ol{text-align:center;}
ol li{display:inline;padding-right:1em;}
ol li a{color:#fff;}
</style>
<body>

<div class="w3-top">
  <div class="w3-row w3-large w3-light-grey">
    <div class="w3-col s3">
      <a href="#" class="w3-button w3-block">Home</a>
    </div>
    <div class="w3-col s3">
      <a href="#plans" class="w3-button w3-block">We need you</a>
    </div>
    <div class="w3-col s3">
      <a href="#about" class="w3-button w3-block">About us</a>
    </div>
    <div class="w3-col s3">
      <a href="#contact" class="w3-button w3-block">Contact</a>
    </div>
    {% if user.is_authenticated %}
    <form class="logout" action="{% url 'accounts:logout'%}" method="POST">
      {% csrf_token %}
      <div class="w3-col s4">
        {% if request|register_or_profile %}
        <a href="{% url 'accounts:ngodetail' %}" class="w3-button w3-block">Go to Profile</a>
        </div>
        <div class="w3-col s4">
        <a href="{% url 'accounts:reset' %}" class="w3-button w3-block"> Reset Password </a>
        </div>
        <div class="w3-col s4">
        <button class="w3-button w3-block" type="submit"> Logout</button>
        </div>
        {% else %}
        <div class="w3-col s4">
        <a href="{% url 'accounts:ngo_register'%}" class="w3-button w3-block">Register your Ngo</a>
        </div>
        <div class="w3-col s4">
        <a href="{% url 'accounts:reset'%}" class="w3-button w3-block">Reset Password </a>
        </div>
        <div class="w3-col s4">
        <button class="w3-button w3-block" type="submit">Logout</button>
        </div>     
      {% endif %}  
  </form>
    {% else %}
    <div class="w3-col s6">
      <a href="{% url 'accounts:signup'%}" class="w3-button w3-block">Signup</a>
    </div>
    <div class="w3-col s6">
      <a href="{% url 'accounts:login'%}" class="w3-button w3-block">Login</a>
    </div>
    {% endif %}
  </div>
</div>



<div class="w3-content" style="max-width:1100px;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h1><b>Beyond Good Intentions</b></h1>
    <h6>World Medical Mission supports mission hospitals by providing equipment, supplies, and technical support. We operate a warehouse that makes shipments to dozens of countries each year. Our biomedical technicians and electrical engineers refurbish donated equipment and also regularly visit mission hospitals to provide field support and maintenance. Machinery and equipment that might be outdated in Western hospitals can be a blessing in a mission hospital, if it is appropriate, functional, and properly installed.</h6>
      
     <h6> World Medical Mission carefully evaluates potential donations to ensure that we send only good quality, useful, and appropriate equipment and supplies. Many mission hospitals are already filled with outdated or broken-down equipment. The last thing we want to do is send more of the same. Although we do appreciate all offers, there will be times when a donation cannot be accepted due to these evaluation standards.</h6>
  </div>


  <div class="w3-container">
    <div class="w3-display-container mySlides">
      <img src="https://pinoythaiyo.com/wp-content/uploads/Coronavirus-Diagnostics1.jpg" style="width:100%">
      <div class="w3-display-topleft w3-container w3-padding-32">
      </div>
    </div>
    <div class="w3-display-container mySlides">
      <img src="https://www.openinnovation.regione.lombardia.it/it/attachments/file/view?hash=058edddb2eef55d68dcf7ba51f94ea2e&canCache=1" style="width:100%">
      <div class="w3-display-middle w3-container w3-padding-32">
      </div>
    </div>
    <div class="w3-display-container mySlides">
      <img src="https://timesofindia.indiatimes.com/thumb/msid-74273245,width-1200,height-900,resizemode-4/.jpg" style="width:100%">
      <div class="w3-display-topright w3-container w3-padding-32">
      </div>
    </div>


    <div class="w3-container w3-dark-grey w3-padding w3-xlarge">
      <div class="w3-left" onclick="plusDivs(-1)"><i class="fa fa-arrow-circle-left w3-hover-text-teal"></i></div>
      <div class="w3-right" onclick="plusDivs(1)"><i class="fa fa-arrow-circle-right w3-hover-text-teal"></i></div>
    
      <div class="w3-center">
        <span class="w3-tag demodots w3-border w3-transparent w3-hover-white" onclick="currentDiv(1)"></span>
        <span class="w3-tag demodots w3-border w3-transparent w3-hover-white" onclick="currentDiv(2)"></span>
        <span class="w3-tag demodots w3-border w3-transparent w3-hover-white" onclick="currentDiv(3)"></span>
      </div>
    </div>
  </div>
  
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Best Donors</span>
    </div>

    <div class="w3-col l12 m6 w3-grey w3-container w3-padding-16">
      <h3>Total Number of Donations</h3>
      <div class="count">
        <h3>Hover over the number</h3>
      </div>
    </div>
    <div class="w3-col l12 m6 w3-light-grey w3-container w3-padding-16">
      <h3>Best Donors</h3>
      {% for user in best_users %}
      <h3>{{ user.0}} {{user.1 }}</h3>
      {% endfor %}
    </div>
  

  <div class="w3-row-padding" id="plans">
    <div class="w3-center w3-padding-64">
      <h3>NGO's out there that need you</h3>
      <ul>
        {% for ngo in ngos %}
        <li>
          <a href="{% url 'accounts:donator' %}">
            <h2>{{ngo.name}}</h2>
            <h2>Founder: {{ngo.founder}}</h2>
            {% for req in ngo.ngorequirementdetail_set.all %}
            {% if req.quantity > 0 %}
            <p>{{req.req}} ({{req.quantity}})</p>
            {% endif %}
            {% endfor %}
          </a>
        </li>
        {% endfor %}
      </ul>
  <div class="w3-row-padding" id="about">
    <div class="w3-center w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Who We Are</span>
    </div>

    <div class="w3-third w3-margin-bottom">
      <div class="w3-card-4">
        <img src="https://pixy.org/src/438/4381589.jpeg" alt="Vinayak" style="width:100%">
        <div class="w3-container">
          <h3>Vinayak Mishra</h3>
          <p class="w3-opacity">Backend Developer</p>
          <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
        </div>
      </div>
    </div>

    <div class="w3-third w3-margin-bottom">
      <div class="w3-card-4">
        <img src="https://i.pinimg.com/originals/f3/8b/ab/f38babe82d458918ccf964f304506393.png" alt="Mayur" style="width:100%">
        <div class="w3-container">
          <h3>Mayur Agarwal</h3>
          <p class="w3-opacity">Backend Developer</p>
          <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
        </div>
      </div>
    </div>

    <div class="w3-third w3-margin-bottom">
      <div class="w3-card-4">
        <img src="https://1.bp.blogspot.com/-KLIG5uQMzH4/XP23oAAjF_I/AAAAAAAACmk/J5FtFxjcK54Rzs8c5hm4YZu5M-9JuplFACLcBGAs/s1600/Dexter%2Bis%2BSUPER%2BADORABLE%2521.jpg" alt="Joshua" style="width:100%">
        <div class="w3-container">
          <h3>Joshua Godinho</h3>
          <p class="w3-opacity">Frontend Developer</p>
          <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
        </div>
      </div>
    </div>
  </div>

  <div class="w3-center w3-padding-64" id="contact">
    <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Contact Us</span>
  </div>

    <form class="w3-container" action="{% url 'accounts:contact' %}" method="post">
    <div class="w3-section">
      <label>Name</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="Name" required>
    </div>
    <div class="w3-section">
      <label>Email</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="Email" required>
    </div>
    <div class="w3-section">
      <label>Subject</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="Subject" required>
    </div>
    <div class="w3-section">
      <label>Message</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="Message" required>
    </div>
    <button type="submit" class="w3-button w3-block w3-black">Send</button>
  </form>

</div>


<footer class="w3-container w3-padding-32 w3-light-grey w3-center">
  <a href="#" class="w3-button w3-black w3-margin"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <div class="w3-xlarge w3-section">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
</footer>


<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demodots");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" w3-white", "");
  }
  x[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " w3-white";
}
</script>

</body>
</html>