Ngo/FinalProj/FinalProj/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()

Ngo/FinalProj/accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('ngo/register/',views.ngo_register,name='ngo_register'),
    path('accountcreate/',views.accountcreate,name='accountcreate'),
    path('ngodetail/',views.ngodetail,name='ngodetail'),
    path('create/', views.edit_view_add, name='edit_view_add'),
    path('delete/',views.delete_view, name='delete_view'),
    path('edit/',views.edit_view, name='edit_view'),
    path('donate/',views.donator_view,name='donator'),
    path('donate/<phone>/',views.donation_confirm,name='don_confirm'),
    path('change-password/', views.MyPasswordChangeView.as_view(), name='reset'),
    path('ngodetail/donators/', views.donators, name='donators'),
    path('donater/signup/',views.d_signup,name='d_signup'),
    path('donators/', views.donators, name='donators'),
    path('contact/',views.contactus, name='contact')
    ]

Ngo/FinalProj/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Ngo(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    founder = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class NgoRequirementDetail(models.Model):
    ngo = models.ForeignKey(Ngo, on_delete=models.CASCADE)
    req = models.CharField(max_length=100)
    quantity = models.IntegerField()

    def __str__(self):
        return self.req


class Donator(models.Model):
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.phone


class DonationDetail(models.Model):
    donator = models.ForeignKey(Donator, on_delete=models.CASCADE)
    ngo = models.ForeignKey(Ngo, on_delete=models.CASCADE)
    req = models.CharField(max_length=100, default='')
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.donator)

Ngo/FinalProj/accounts/forms.py
from django import forms
from .models import Ngo, NgoRequirementDetail, Donator, DonationDetail


class NgoRegisterForm(forms.ModelForm):
    class Meta:
        model = Ngo
        fields = ['name', 'email', 'phone']


class AddRequirement(forms.ModelForm):
    class Meta:
        model = NgoRequirementDetail
        fields = ['req', 'quantity']


class DonatorForm(forms.ModelForm):
    class Meta:
        model = Donator
        fields = ['first_name', 'last_name', 'phone']


class DonationConfirmForm(forms.ModelForm):
    class Meta:
        model = DonationDetail
        fields = ['ngo', 'req', 'quantity']

Ngo/FinalProj/accounts/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from . import forms
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Ngo, NgoRequirementDetail
from django.contrib import messages
from .models import Donator, DonationDetail
from .forms import NgoRegisterForm, DonationConfirmForm
from django.views.decorators.csrf import csrf_exempt


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:accountcreate')
            # user logged in hona chaiye
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


def ngo_register(request):
    form = NgoRegisterForm()
    if request.method == 'POST':
        form = NgoRegisterForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.founder = request.user
            instance.save()
            return redirect('home')
    return render(request, 'accounts/ngoregister.html', {'form': form})


def accountcreate(request):
    return render(request, 'accounts/accountcreated.html')


def donator_view(request):
    if request.method == 'POST':
        form = forms.DonatorForm(request.POST)
        if form.is_valid():
            don = form.save()
            phone = don.phone
            return redirect('accounts:don_confirm', phone=phone)
    else:
        form = forms.DonatorForm()
    return render(request, 'accounts/donator.html', {'form': form})


@login_required(login_url='accounts:login')
def ngodetail(request):
    ngo = get_object_or_404(Ngo, founder=request.user)
    return render(request, 'accounts/ngodetail.html', {'ngo': ngo})


def donation_confirm(request, phone):
    if request.method == 'POST':
        form = DonationConfirmForm(request.POST)
        if form.is_valid():
            ins = form.save(commit=False)
            myngo = ins.ngo
            val = myngo.ngorequirementdetail_set.all().filter(req=ins.req)
            if not val:
                messages.info(request, "Selected ngo does'nt need this requirement.")
                return redirect('accounts:don_confirm', phone=phone)
            else:
                req = myngo.ngorequirementdetail_set.get(req=ins.req)
                if req.quantity == 0:
                    messages.info(request, "Selected ngo does'nt need this requirement.")
                    return redirect('accounts:don_confirm', phone=phone)
                elif req.quantity < ins.quantity:
                    messages.info(request, f'{ins.ngo} needs only {req.quantity} quantity of {ins.req}')
                    return redirect('accounts:don_confirm', phone=phone)
                else:
                    req.quantity -= ins.quantity
                    req.save()
                    dins = Donator.objects.get(phone=phone)
                    ins.donator = dins
                    ins.save()
                    return redirect('home')
    else:
        form = DonationConfirmForm()
    return render(request, 'accounts/donate_confirm.html', {'phone': phone, 'form': form})


@login_required(login_url='/accounts/login/')
def edit_view_add(request):
    if request.method == 'POST':
        form = forms.AddRequirement(request.POST)
        if form.is_valid():
            # save article to db form.save()
            instance = form.save(commit=False)
            myngo = Ngo.objects.get(founder=request.user)
            val = myngo.ngorequirementdetail_set.all().filter(req=instance.req)
            if val:
                ins = NgoRequirementDetail.objects.get(ngo=myngo, req=instance.req)
                ins.quantity = instance.quantity
                ins.save()
            else:
                instance.ngo = myngo
                instance.save()

            return redirect('home')
    else:
        form = forms.AddRequirement()
    return render(request, 'accounts/add_requirement.html', {'form': form})


@login_required(login_url='/accounts/login/')
def delete_view(request):
    if request.method == 'POST':
        req = request.POST.get('req')
        myngo = Ngo.objects.get(founder=request.user)
        val = myngo.ngorequirementdetail_set.all().filter(req=req)
        if not val:
            messages.success(request, f'You Entered the Requirement which is NOT present in your NGO, Try Again!')
            return redirect('accounts:delete_view')
        else:
            ins = NgoRequirementDetail.objects.get(ngo=myngo, req=req)
            ins.quantity = 0
            ins.save()
            return redirect('accounts:ngodetail')
    else:
        return render(request, 'accounts/delete.html')


@login_required(login_url='/accounts/login/')
def edit_view(request):
    if request.method == 'POST':
        requirement = request.POST.get('requirement')
        quantity = request.POST.get('quantity')
        myngo = Ngo.objects.get(founder=request.user)
        val = myngo.ngorequirementdetail_set.all().filter(req=requirement)
        if not val:
            messages.success(request, f'You Entered the Requirement which is NOT present in your NGO, Try Again!')
            return redirect('accounts:edit_view')
        else:
            ins = NgoRequirementDetail.objects.get(ngo=myngo, req=requirement)
            ins.quantity = quantity
            ins.save()
            return redirect('accounts:ngodetail')
    else:
        return render(request, 'accounts/edit.html')


@login_required(login_url='/accounts/login/')
def donators(request):
    dds = DonationDetail.objects.all()
    myngo = Ngo.objects.get(founder=request.user)
    return render(request, 'accounts/donators.html', {'dds': dds, 'myngo': myngo})


class MyPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/resetp.html'
    success_url = reverse_lazy('home')


def d_signup(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        val = False
        for don in Donator.objects.all():
            if don.phone == phone:
                val = True
                break
        if val:
            return redirect('accounts:don_confirm', phone=phone)
        else:
            return redirect('accounts:donator')
    else:
        return render(request, 'accounts/d_signup.html')


@csrf_exempt
def contactus(request):
    if request.method == 'POST':
        email = request.POST.get('Email')
        subject = request.POST.get('Subject')
        message = request.POST.get('Message')
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email]
        )
        return render(request, 'home.html')
    return redirect('home')

Ngo/FinalProj/accounts/templates/accounts/accountcreated.html
<html>
    <head>
        <style>
            body{
                background-color: black;
            }
            ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
        </style>
    </head>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
    </ul>
<div style="padding-top:300px;" align="center" class="container">
<h1 style="color: whitesmoke;">Your account was created successfully</h1>
<button style="padding: 10px;" ><a style="font-weight: bolder; color: black; text-decoration:none;font-family: 'Times New Roman', Times, serif;" href="{% url 'accounts:ngo_register' %}">Go Ahead Register your NGO</a></button>
</div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/add_requirement.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Requirement</title>
    <style>
        body{
            background-color: black;
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'accounts:ngodetail' %}">Go to Profile</a></li>
    </ul>
    <div style="padding-left: 200px;">
        <h1 style=" padding-top: 50px; color: whitesmoke;">Your NGO needs some more?</h1>
        <h2 style="color: whitesmoke;">Add Your Requirement here</h2>
        <form style="font-size: larger; font-weight: 800; padding-top: 10px; color: whitesmoke;" action = "{% url 'accounts:edit_view_add' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <div style="padding-top: 10px;" class="button">
        <button style="font-size:large; padding-top:5px" type="submit">Add Requirement</button>
        </div>
        </form>
    </div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/d_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DonaterInfo</title>
    <style>
        body{
            background-image: url(https://images.pexels.com/photos/1040499/pexels-photo-1040499.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
    </ul>
    <div style="padding-left: 60px; padding-top: 40px;" class="container">
    <h2 style="color: whitesmoke;">Confirm your Phone Number</h2>
    <form action="{% url 'accounts:d_signup' %}" method="POST">
        {% csrf_token %}
        <strong style="font-size:x-large; color: whitesmoke;">Phone no : </strong><input type='text' name='phone'>
        <input style="margin-left: 20px;font-family:'Times New Roman', Times, serif;font-size: large;" type='submit' value='Enter'> 
    </form>
</div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Requirement</title>
</head>
<style>
    body{
        background-image: url(https://images.pexels.com/photos/910213/pexels-photo-910213.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
        background-attachment: fixed;
    }
    ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
</style>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'accounts:ngodetail' %}">Go to Profile</a></li>
    </ul>
<div style="padding-top: 50px; padding-left:100px" class="container">
    <div>
        <h1>Already have what you want?</h1>
        {% if messages %}
            {% for message in messages %}
                <h4 align="center">{{message}}</h4>
            {% endfor %}
        {% endif %}
    </div>
    <form action="{% url 'accounts:delete_view' %}" method="post">
        {% csrf_token %}
           <h2>Enter the name of the Requirement you wish to delete : </h2> <input type="text" name="req">
        <div style=" padding-top: 20px;"> 
        <button style="font-size:large;" type="submit">Delete</button>
        </div>
    </form>
</div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/donate_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation Confirm</title>
    <style>
        body{
            background-image: url(https://images.pexels.com/photos/919700/pexels-photo-919700.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
        }
        .container {
        width: 100%;
        height: 100%;
        }
        .box {
        border: 1px solid #fff;
        padding: 50px;
        width: 500px;
        background-color: #fff;
        opacity: 0.7;
        font-weight: bolder;
        }ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
    </ul>
    <div align="center" class="container">
        {% if messages %}
          {% for message in messages %}
          <h3>{{message}}</h3>
          {% endfor %}
        {% endif %}
        <div align="left" class="box">
        <h1>Donation Confirmation Details</h1>
        <form style="font-size:x-large;" action="{% url 'accounts:don_confirm' phone=phone %}" method='POST'>     
            {% csrf_token %}
            {{form.as_p}}
            <div align="center" class="button">
            <input style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: x-large;" type='submit' value='Next'>
            </div>
            </form>
        </div>
    </div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/donator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donator</title>
    <style>
        body{
            background-repeat: no-repeat;
            background-image: url(https://images.pexels.com/photos/917494/pexels-photo-917494.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
        }
        .container {
        width: 100%;
        height: 100%;
        }
        .box {
        border: 1px solid #fff;
        padding: 50px;
        width: 200px;
        background-color: #fff;
        opacity: 0.7;
        font-weight: bolder;
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body>
    <ul>
            <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
            <li><a href="{% url 'accounts:d_signup' %}">Already a Donator?</a></li>
    </ul>
    
    <form action="{% url 'accounts:donator' %}" method='POST'>
    <div align="center" class="container">
        <div align="left" class="box">
        <form action="{% url 'accounts:donator' %}" method='POST'> 
            {% csrf_token%}
            {{form.as_p}}
            <div style="padding-top: 5px;padding-left: 60px;" class="button">
            <input style="padding:3px 6px;font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;font-size: large   ;" type='submit' value='Next'>
            </div>
            </form>
        </div>
    </div>
</form>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/donators.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Donators</title>
    <style>
        body{
            background-image: url(https://images.pexels.com/photos/1831234/pexels-photo-1831234.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
        }
        .container {
        width: 100%;
        height: 100%;
        padding-left:100px;
        }
        .box {
        font-size: x-large;
        border: 1px solid #fff;
        padding: 50px;
        width: 400px;
        background-color: #fff;
        opacity: 0.7;
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body>
    <ul>
        <li data-text="Home"><a href="{% url 'accounts:ngodetail' %}">Go to Profile</a></li>
    </ul>
    <div class="container">
        <div class="box">
        {% for dd in dds %}
            {% if dd.ngo == myngo %}
                <p>Donor Name: {{ dd.donator.first_name }} {{dd.donator.last_name}}</p>
                <p>Equipment Provided:{{ dd.req }}</p>
                <p>Quantitiy: {{ dd.quantity }}</p>
            {% endif %}
        {% endfor %}
    </div>
</div>
</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/login.html
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>  

    <h1 align="center"
    style="padding-top: 80px;padding-bottom: 10px;font-weight: 600;font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; background-color:#66d9ff";>Login</h1>
    <div class="container-fluid" align="center"
    style="padding-top: 150px;
    padding-bottom: 50px;
     background-color:#ccf2ff">
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {%csrf_token%}
        <p class="text-white">{{ form.as_p }}</p>
        {% if request.GET.next%}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button 
        style="background-color: white;
        color: black;
        border: 2px solid black;"
        type="submit" class="btn btn-primary">Login</button>
    </form>
    </div>

</body>
</html>

Ngo/FinalProj/accounts/templates/accounts/ngodetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ngo Detail</title>
    <style>
        body{
            background-image: url(https://remotesitesolutions.com/newsite/wp-content/uploads/2013/02/remote-site-solutions-bg_ngo-sector.jpg);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .container {
        width: 100%;
        height: 100%;
        }
        .box {
        border: 1px solid #fff;
        padding: 50px;
        width: 250px;
        background-color: #fff;
        opacity: 0.7;
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body >
        {% if user.is_authenticated %}
        <ul>
            <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
            <li data-text="Want to see your donators?"><a href="{% url 'accounts:donators' %}">Want to see your donators?</a></li>
            <li data-text="Add Requirement"><a href="{% url 'accounts:edit_view_add' %}">Add Requirement</a></li>
            <li data-text="Edit your Requirement"><a href="{% url 'accounts:edit_view' %}">Edit your Requirement</a></li>
            <li data-text="Delete your Requirement"><a href="{% url 'accounts:delete_view' %}">Delete your Requirement</a></li>
        </ul>
        {% endif %}
    <div align="center" class="container">
        <div align="left" class="box">
    <h1>{{ngo.name}}</h1>
    <div></div>
    <h2>Founder: {{ngo.founder}}</h2>
    <div></div>
    {% for req in ngo.ngorequirementdetail_set.all %}
    {% if req.quantity > 0 %}
    {{req.req}}
    ({{req.quantity}})
    <div></div>
    {% endif %}
    {% endfor %}
    </div>
</div>
   
</body>
</html>

    

Ngo/FinalProj/accounts/templates/accounts/ngoregister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NgoRegister</title>
    <style>
        body{
            background-image: url(https://www.3dspectratech.com/wp-content/uploads/2016/05/page-background-testimonials.jpg);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .button {
         transition-duration: 0.4s;
         padding-top: 40px;
        }
        ul{
            padding-top: 10px;
            padding-left: 50px;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        ul li{
            padding-top: 10px;
            list-style: none;
        }
        ul li a{
            position: relative;
            display: inline-block;
            padding: 10px 15px;
            text-decoration: none;
            background:#000000;
            color: #fff;
            text-transform: uppercase;
            letter-spacing: 2px;
            overflow: hidden;
            transition: 0.5s;
            z-index: 1;
        }
        ul:hover li a{
            opacity: 0.5;
        }
        ul li a:hover{
            transform: scale(1.4);
            z-index: 1000;
            background: #ff3f81;
            opacity: 1;
        }
    </style>
</head>
<body align="center">
    <ul align="left">
        <li data-text="Home"><a href="{% url 'home' %}">Go to Homepage</a></li>
    </ul>
    <div style="color: whitesmoke;font-size: xx-large;" class="container">
        <h1>Register your NGO</h1>
        <div style="padding-top: 50px;" class="form">
        <form action="{% url 'accounts:ngo_register' %}" method='POST'>
            {% csrf_token %}
                {{form.as_p}}
            <div class="button">
            <button style="
            font-family: Georgia, 'Times New Roman', Times, serif;
            padding: 5px;
            background-color: white;
            color: black;
            border: 2px solid white; font-size: x-large;" type='submit'>Register</button>
            </div>
    </form>
    </div>
    <div>
</body>
</html>